### ISSUE TITLE
Server version: 1.8.3R0, api implementation: 1.8R3, broken

### ISSUE THREAD

**Issue by Songbird0** [Cybermaxke/MerchantsAPI#8]
Hi there,

Implementation compatibilty broken.

I tried this code:

```java
        merchants_api = Merchants.get();
        assert(merchants_api != null) : "merchants_api == " + merchants_api;
```

I expected to see this happen: assertion success

Instead, this happened: `Merchants.get()` method return `null`.

## Meta

Backtrace:

```
[16:20:13 INFO]: [Merchants] Enabling Merchants v1.4.0-SNAPSHOT
[16:20:13 WARN]: [Merchants] Plugin could not be loaded, version {v18r2} is not supported!
[16:20:13 INFO]: [WorldEdit] Enabling WorldEdit v6.1;no_git_id
[16:20:13 INFO]: WEPIF: Using the Bukkit Permissions API.
[16:20:13 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R2 as the Bukkit adapter
[16:20:13 INFO]: [Rush] Enabling Rush v0.114.15-snapshot
[16:20:13 INFO]: DEBUGClose : new game a7fa3f45-80a3-40d9-8b3a-06cdbaeec800
[16:20:13 ERROR]: Error occurred while enabling Rush v0.114.15-snapshot (Is it up to date?)
java.lang.AssertionError: merchants_api == null
    at fr.??.rush.Rush.<init>(Rush.java:183) ~[?:?]
    at fr.??.rush.BootstrapPlugin.onEnable(BootstrapPlugin.java:29) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
    at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
    at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
    at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
    at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
    at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
    at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
    at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.8.3.jar:git-Spigot-870264a-0a645a2]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[16:20:13 INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:20:13 INFO]: Done (1,751s)! For help, type "help" or "?"
```

Why this implementation don't work ? :(

Thanks.

**Comment by Songbird0** [comment]
cc @Cybermaxke

**Comment by Cybermaxke** [comment]
The r3 is the revision used internally by spigot, revision 3 was released with 1.8.4, not 1.8.3.

**Comment by Songbird0** [comment]
Indeed. I'll submit a pull request soon, if you want.

**Comment by Cybermaxke** [comment]
Only the latest revision of every major minecraft version should be supported, I don't really see a point in having support for all the other ones.
